---

- name: import basic roles for buster
  include: buster_basic.yml
  when: ansible_distribution == 'Debian' and ansible_distribution_version == '10'

- name: import basic roles for stretch
  include: stretch_basic.yml
  when: ansible_distribution == 'Debian' and ansible_distribution_version == '9.9'

