---
- name: Create postgres user
  become: yes
  become_user: postgres
  postgresql_user:
    name: "ckan_default"
    password: "ckan123"

- name: create ckan db
  become: yes
  become_user: postgres
  postgresql_db:
    name: ckan_default
    encoding: UTF-8

- name: Ensure CKAN database exists
  become_user: postgres
  become: yes
  postgresql_db:
    name: "ckan_default"
    encoding: UTF-8
    template: template0

- name: Ensure CKAN database user exists
  become_user: postgres
  become: yes
  postgresql_user:
    db: "ckan_default"
    name: "ckan_default"
    password: "{{ db_password }}"
    priv: ALL
#
#- name: Allow Apache to connect to Postgresql
#  seboolean:
#    name: httpd_can_network_connect_db
#    state: yes
#    persistent: yes
#- name: Allow Apache to connect to Redis and SOLR
#  seboolean:
#    name: httpd_can_network_connect
#    state: yes
#    persistent: yes
#- name: Allow Apache to listen on port 8983 for Solr
#  seport:
#    ports: 8888
#    proto: tcp
#    setype: http_port_t
#    state: present
