---
# file playbook-ckan.yml

- hosts: all
  vars:
    allow_world_readable_tmpfiles: true
  roles:
    - basics
    - meta
    - postgres
    - ckan
    - redis
    - solr
    - deploy


#when: ansible_distribution == 'CentOS' and ansible_distribution_version == '6.4'