---

#- name: restart jetty9
#  service:
#    name: jetty9
#    state: restarted
#- name: Creates directory
#  file:
#    path: ~/ckan/lib
#    state: directory
#- name: Create sym link
#  file:
#    src: ~/ckan/lib
#    dest: /usr/lib/ckan
#    state: link
#- name: Creates ckan-etc
#  file:
#    path: ~/ckan/etc
#    state: directory
#- name: Creates ckan-etc sym link
#  file:
#    src: ~/ckan/etc
#    dest: /etc/ckan
#    state: link
#
#- debug: msg="{{ solrschemamv.stdout_lines }}"
#
#- debug: msg="{{ solrschemaln.stdout_lines }}"
#
#- debug: msg="{{ whoini.stdout_lines }}"
#
#- debug: msg="{{ dbinit.stdout_lines }}"

handlers:
    - name: Restart Apache
      service: name=apache2 state=restarted

    - name: Restart Nginx
      service: name=nginx state=restarted

    - name: Start Jetty
      service: name=jetty state=started

    - name: Restart Jetty
      service: name=jetty state=restarted
