---

- name: import solr roles for buster
  include: buster_solr.yml
  when: ansible_distribution == 'Debian' and ansible_distribution_version == '10'

- name: import solr roles for stretch
  include: stretch_solr.yml
  when: ansible_distribution == 'Debian' and ansible_distribution_version == '9.9'