---

- name: Download Solr 6.5.1 archive
  become: true
  become_user: ckan
  get_url:
    url: https://archive.apache.org/dist/lucene/solr/6.5.1/solr-6.5.1.tgz
    dest: /home/ckan/solr-6.5.1.tgz
    checksum: sha256:7c6a7d4474d5e847a8ddd0a4717d33bf5db07adf17c3d36ad1532c72885bd5d3
    force: no

- name: Expand Solr archive
  become: true
  become_user: root
  become_method: sudo
  unarchive:
    src: /home/ckan/solr-6.5.1.tgz
    dest: /home/ckan/
    copy: no

- name: Run Solr installation script
  become: true
  become_user: root
  become_method: sudo
  shell: /home/ckan/solr-6.5.1/bin/install_solr_service.sh /home/ckan/solr-6.5.1.tgz
    creates=/opt/solr/bin/solr

- name: change owner (and group)
  become: true
  become_user: root
  become_method: sudo
  file:
    path: /opt/solr-6.5.1
    owner: solr
    recurse: true

- name: change owner (and group)
  become: true
  become_user: root
  become_method: sudo
  file:
    path: /var/solr
    owner: solr
    recurse: true

- name: check ckan core exists
  become: true
  become_user: root
  become_method: sudo
  stat:
    path: /var/solr/data/ckan/
  register: cor

- name: Create Solr CKAN configuration
  become: true
  become_user: solr
  shell: ./solr create_core -c ckan
  args:
    chdir: /opt/solr-6.5.1/bin/
  when: cor.stat.exists == False

- name: copy ckan schema to new solr core
  become: yes
  become_user: solr
  become_method: sudo
  template:
    src: ../../templates/default/solr/solr6/schema.xml.j2
    dest: /var/solr/data/ckan/conf/solr6/schema.xml
  register: symnewschema

- name: Clean managed schema
  become: yes
  become_user: solr
  file:
    state: absent
    path: "/var/solr/data/ckan/conf/managed-schema"

- name: copy solrconfig
  become: yes
  become_user: solr
  become_method: sudo
  template:
    src: ../../templates/default/solr/solr6/solrconfig.xml.j2
    dest: /var/solr/data/ckan/conf/solr6/solrconfig.xml
  register: solrconf

- name: Initialize CKAN database
  become_user: root
  become: yes
  shell: |
    . /usr/lib/ckan/default/bin/activate
    cd /usr/lib/ckan/default/src/ckan
    paster db init -c /etc/ckan/default/development.ini
    exit

- name: Check if CKAN admin user exists
  become_user: ckan
  become: yes
  shell: |
    . /usr/lib/ckan/default/bin/activate
    cd /usr/lib/ckan/default/src/ckan
    paster --plugin=ckan user list -c /etc/ckan/default/development.ini
    exit
  changed_when: False
  register: ckan_admin_user

- name: ----- Create admin account -----
  become_user: ckan
  become: yes
  shell: |
    . /usr/lib/ckan/default/bin/activate
    cd /usr/lib/ckan/default/src/ckan
    echo 'y' | paster sysadmin add ckan email=ckan@localhost password=12345678 name=ckan -c /etc/ckan/default/development.ini
    exit

- name: Ensure Solr is enabled on boot
  service:
    name: solr
    enabled: yes

- name: Restart solr
  become: yes
  become_user: root
  service:
    name: solr
    state: restarted