---

- name: Update apt
  apt: update_cache=yes
  become: true
  become_user: root
  become_method: sudo

- name: Upgrade all safe packages
  become: true
  become_user: root
  become_method: sudo
  apt: upgrade=safe

# Install Python Stuff
- name: Install python-dev, python-pip, python-virtualenv
  become: true
  become_user: root
  become_method: sudo
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - python2.7
    - python-pip
    - python-virtualenv
# Install Services
- name: Install services and tools
  become: true
  become_user: root
  become_method: sudo
  apt: pkg={{ packages }} state=installed
  with_items:
    - libpq-dev
    - git-core
    - openjdk-7-jdk
    - postgresql
    - redis-server
    - solr-jetty
    - wget
# Install libpq
#- name: Install libpq
#  become: true
#  become_user: root
#  become_method: sudo
#  apt:
#    name: libpq-dev
# Install Git
#- name: Install git-core
#  become: true
#  become_user: root
#  become_method: sudo
#  apt:
#    name: git-core
# Install Database
#- name: postgresql
#  become: true
#  become_user: root
#  become_method: sudo
#  apt:
#    name: postgresql
# Install Redis
#- name: redis-server
#  become: true
#  become_user: root
#  become_method: sudo
#  apt:
#    name: redis-server
# Install solr-jetty or solr-tomcat
#- name: solr-jetty || solr-tomcat
#  become: true
#  become_user: root
#  become_method: sudo
#  apt:
#    name: solr-jetty