---
#- name: update
#  apt: update_cache=yes
#  become: yes
#  become_method: sudo
# Install Python Stuff
- name: Install python-dev, python-pip, python-virtualenv
  become: true
  become_user: root
  become_method: sudo
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - python2.7
    - python-pip
    - python-virtualenv
# Install JDK
- name: Install Java 7
  become: true
  become_user: root
  become_method: sudo
  apt:
    name: openjdk-7-jdk
# Install libpq
- name: Install libpq
  become: true
  become_user: root
  become_method: sudo
  apt:
    name: libpq-dev
# Install Git
- name: Install git-core
  become: true
  become_user: root
  become_method: sudo
  apt:
    name: git-core
# Install Database
- name: postgresql
  become: true
  become_user: root
  become_method: sudo
  apt:
    name: postgresql
# Install Redis
- name: redis-server
  become: true
  become_user: root
  become_method: sudo
  apt:
    name: redis-server
# Install solr-jetty or solr-tomcat
- name: solr-jetty || solr-tomcat
  become: true
  become_user: root
  become_method: sudo
  apt:
    name: solr-jetty