---
#Install setuptools for ckan
- name: Setuptools
  become: true
  become_user: root
  become_method: sudo
  pip:
    name: setuptools==36.1
    virtualenv: /usr/lib/ckan/default

#Install ckan - hint: you can also change the version of ckan in this string
- name: Install ckan
  become: true
  become_user: root
  become_method: sudo
  pip:
    name: git+https://github.com/ckan/ckan.git@ckan-2.8.2#egg=ckan
    virtualenv: /usr/lib/ckan/default

#Install requirements
- name: requirements
  become: true
  become_user: root
  become_method: sudo
  pip:
    requirements: pip install -r /usr/lib/ckan/default/src/ckan/requirements.txt
    virtualenv: /usr/lib/ckan/default