---

- name: Inculde tasks vars
  include_vars:
    file: vars/vars.yml

- name: software packages
  import_tasks: root/installation_software.yml
  tags: root
- import_tasks:  root/install_ckan_env.yml
  tags: root
- import_tasks: non-root/ckan_postgres.yml
  tags: non-root
- import_tasks:  root/ckan_dev_ini.yml
  tags: root
- import_tasks: root/jetty_solr_config.yml
  tags: root
- import_tasks: root/who_ini.yml
  tags: root

