---

- name: Ensure group "wheel" exists
  become: true
  become_user: root
  become_method: sudo
  group:
    name: wheel
    state: present

#- name: Ensure CKAN user exists
#  become: true
#  become_user: root
#  become_method: sudo
#  user:
#    name: ckan
#    comment: "CKAN User"
#    home: /usr/lib/ckan
#    shell: /bin/bash
#    groups: wheel
#    append: yes

- name: Allow 'wheel' group to have passwordless sudo
  become: true
  become_user: root
  become_method: sudo
  lineinfile:
    dest: '/etc/sudoers'
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'

- name: Inculde tasks vars
  include_vars:
    file: vars/vars.yml

- name: software packages
  import_tasks: root/basics/installation_software.yml
  tags: root
- import_tasks: non-root/ckan_postgres.yml
  tags: non-root
- import_tasks: root/ckan_dev_ini.yml
  tags: root
- import_tasks: root/install_ckan_env.yml
  tags: root
- import_tasks: root/solr/jetty_solr_config.yml
  tags: root


#### Deploy Tasks
- import_tasks: root/post_install_config.yml
  tags: root






