---

# Create ckan_default and grant access to database

- name: "Create foreman PostgreSQL user"
  become: true
  become_user: postgres
  become_method: su
  command: postgres createuser -S -D -R -P ckan_default


#  postgresql_user:
#      db: ckan_default
#      name: ckan_default
#      password: ckan123
#      priv: All
#      expires: infinity

# Create database for ckan
- name: "Create db"
  become: true
  become_user: postgres
  become_method: su
  command: postgres createdb -O ckan_default ckan_default -E utf-8

#  postgresql_db:
#     name: ckan_default
#     encoding: UTF-8
#     lc_collate: de_DE.UTF-8
#     lc_ctype: de_DE.UTF-8
#     owner: ckan_default
