---


- name: Create postgres user
  become: yes
  become_user: postgres
  postgresql_user:
    name: "ckan_default"
    password: "ckan123"

- name: create ckan db
  become: yes
  become_user: postgres
  postgresql_db:
    name: ckan_default
    encoding: UTF-8