---

- name: Download Solr 6.5.1 archive
  become: true
  become_user: ckan
  get_url:
    url: https://archive.apache.org/dist/lucene/solr/6.5.1/solr-6.5.1.tgz
    dest: /home/ckan/solr-6.5.1.tgz
    checksum: sha256:7c6a7d4474d5e847a8ddd0a4717d33bf5db07adf17c3d36ad1532c72885bd5d3
    force: no


- name: Expand Solr archive
  become: true
  become_user: root
  become_method: sudo
  unarchive:
    src: /home/ckan/solr-6.5.1.tgz
    dest: /home/ckan/
    copy: no

- name: Run Solr installation script
  become: true
  become_user: root
  become_method: sudo
  shell: /home/ckan/solr-6.5.1/bin/install_solr_service.sh /home/ckan/solr-6.5.1.tgz
    creates=/opt/solr/bin/solr

- name: change owner (and group)
  become: true
  become_user: root
  become_method: sudo
  file:
    path: /opt/solr-6.5.1
    owner: solr
    recurse: true

- name: change owner (and group)
  become: true
  become_user: root
  become_method: sudo
  file:
    path: /var/solr
    owner: solr
    recurse: true


#su -u solr -c "/opt/solr/bin/solr create_core -c mycore"

#- name: Remove the Solr installation files
#  file:
#    path: "{{ item }}"
#    state: absent
#  with_items:
#    - ~/solr-6.5.1.tgz
#    - ~/solr-6.5.1/
#
#su -u solr -c

##
##
#- name: Ensure managed-schema is absent
#  file:
#    path: '/var/solr/data/ckan/conf/managed-schema'
#    state: absent
#
#
#- name: Ensure solrconfig.xml for CKAN is present
#  template:
#    src: "solrconfig.xml"
#    dest: "/var/solr/data/ckan/conf/solrconfig.xml"
#
#
# Solr might not be running as a system service, so don't invoke systemd
#- name: Ensure Solr is stopped
#  shell: service solr stop
#
#
#- name: Ensure Solr deamon is reloaded
#  systemd:
#    name: solr
#    daemon_reload: yes
#  when: solr_installed.changed
#
#
#- name: Ensure Solr is enabled on boot
#  service:
#    name: solr
#    enabled: yes

- name: Define Jetty Port
  become: yes
  become_user: root
  become_method: sudo
  lineinfile:
    dest: '/etc/jetty9/start.ini'
    regexp: jetty.port
    line: 'jetty.port = 8983'

- name: Define Jetty host
  become: yes
  become_user: root
  become_method: sudo
  lineinfile:
    dest: '/etc/jetty9/start.ini'
    regexp: jetty.host
    line: 'jetty.host = 127.0.0.1'

- name: Define Jetty start
  become: yes
  become_user: root
  become_method: sudo
  lineinfile:
    dest: '/etc/jetty9/start.ini'
    regexp: NO_START
    line: 'NO_START = 0'
- name: solr schema
  become: yes
  become_user: root
  become_method: sudo
  command: mv /etc/solr/conf/schema.xml /etc/solr/conf/schema.xml.bak

- name: solr schema copy
  become: yes
  become_user: root
  become_method: sudo
  shell: ln -s /usr/lib/ckan/default/src/ckan/ckan/config/solr/schema.xml /etc/solr/conf/schema.xml


- name: check solr jetty xml
  stat:
    path: /var/lib/jetty9/webapps/solr.xml
  register: sj

- name: solr jetty xml copy
  become: yes
  become_user: root
  become_method: sudo
  command: ln -s /etc/solr/solr-jetty.xml /var/lib/jetty9/webapps/solr.xml
  when: sj.stat.islnk == false

- name: check ckan core exists
  become: true
  become_user: root
  become_method: sudo
  stat:
    path: /var/solr/data/ckan/
  register: ckcore

- name: Create Solr CKAN configuration
  become: true
  become_user: solr
  shell: ./solr create_core -c ckan creates=/var/solr/data/ckan/conf/solrconfig.xml
  args:
    chdir: /opt/solr-6.5.1/bin/
  when: ckcore.stat.exists == false

- name: Copy Solr Config
  become: true
  become_user: root
  become_method: sudo
  template:
    src: ../../../templates/default/solr/solrconfig.xml
    dest: /var/solr/data/ckan/conf

- name: Remove solr managed-schema
  file:
    path: /usr/lib/ckan/default/src/ckan/ckan/config/solr/managed-schema
    state: absent

- name: copy ckan schema to new solr core
  become: yes
  become_user: solr
  become_method: sudo
  shell: cp /usr/lib/ckan/default/src/ckan/ckan/config/solr/schema.xml /var/solr/data/ckan/conf/schema.xml
  register: symnewschema

- name: Initialize CKAN database
  become_user: root
  become: yes
  shell: |
    . /usr/lib/ckan/default/bin/activate
    cd /usr/lib/ckan/default/src/ckan
    paster db init -c /etc/ckan/default/development.ini
    exit
- name: Check if CKAN admin user exists
  become_user: ckan
  become: yes
  shell: |
    . /usr/lib/ckan/default/bin/activate
    cd /usr/lib/ckan/default/src/ckan
    paster --plugin=ckan user list -c /etc/ckan/default/development.ini
    exit
  changed_when: False
  register: ckan_admin_user

- name: Ensure Solr is enabled on boot
  service:
      name: solr
      enabled: yes
