---

- name: Define Jetty Port
  become: yes
  become_user: root
  become_method: sudo
  lineinfile:
    dest: '/etc/jetty9/start.ini'
    regexp: jetty.port
    line: 'jetty.port = 8983'

- name: Define Jetty host
  become: yes
  become_user: root
  become_method: sudo
  lineinfile:
    dest: '/etc/jetty9/start.ini'
    regexp: jetty.host
    line: 'jetty.host = 127.0.0.1'

- name: Define Jetty start
  become: yes
  become_user: root
  become_method: sudo
  lineinfile:
    dest: '/etc/jetty9/start.ini'
    regexp: NO_START
    line: 'NO_START = 0'

