---

#- name: Create postgres user
#  become: yes
#  become_user: root
#  postgresql_user:
#    name: "postgres"
#    password: "ckan123"
#    state: present

- name: Create ckan user
  become: yes
  become_user: postgres
  postgresql_user:
    name: "ckan_default"
    password: "ckan123"
    state: present

- name: create ckan db
  become: yes
  become_user: postgres
  postgresql_db:
    name: ckan_default
    encoding: UTF-8

- name: Ensure CKAN database exists
  become_user: postgres
  become: yes
  postgresql_db:
    name: "ckan_default"
    encoding: UTF-8
    template: template0

- name: Ensure CKAN database user exists
  become_user: postgres
  become: yes
  postgresql_user:
    db: "ckan_default"
    name: "ckan_default"
    password: "{{ db_password }}"
    priv: ALL

