---

- name: copy dev.ini
  become: yes
  become_user: root
  become_method: sudo
  copy:
    remote_src: no
    src: '../../templates/default/ckan/development.ini'
    dest: /etc/ckan/default/

- name: copy jetty9 default
  become: yes
  become_user: root
  become_method: sudo
  copy:
    remote_src: no
    src: '../../templates/default/jetty9/jetty9'
    dest: /etc/default/

- name: Define sql connection
  become: yes
  become_user: root
  become_method: sudo
  lineinfile:
    dest: '/home/ckan/ckan/etc/default/development.ini'
    regexp: sqlalchemy.url
    line: 'sqlalchemy.url = postgresql://ckan_default:ckan123@localhost/ckan_default'

- name: Define site id
  become: yes
  become_user: root
  become_method: sudo
  lineinfile:
    dest: '/etc/ckan/default/development.ini'
    regexp: ckan.site_id
    line: 'line=ckan.site_id = default'

- name: Define site url
  become: yes
  become_user: root
  become_method: sudo
  lineinfile:
    dest: '/etc/ckan/default/development.ini'
    regexp: ckan.site_url
    line: 'ckan.site_url = http://localhost'

- name: Define solr url
  become: yes
  become_user: root
  become_method: sudo
  lineinfile:
    dest: '/etc/ckan/default/development.ini'
    regexp: solr_url
    line: 'solr_url = http://localhost:8983/solr/ckan'

- name: Define Storage path
  become: yes
  become_user: root
  become_method: sudo
  lineinfile:
    dest: '/etc/ckan/default/development.ini'
    regexp: ckan.storage_path
    line: 'ckan.storage_path = /var/lib/ckan/default'

