---

#Create Ckan data structure
- name:  ckan data structure
  become: true
  become_user: root
  become_method: sudo
  command: paster db init -c /etc/ckan/default/development.ini
  args:
    chdir:  /usr/lib/ckan/default/src/ckan/