---

#Install setuptools for ckan
- name: Setuptools
  become: true
  become_user: root
  become_method: sudo
  pip:
    name:
      - setuptools==36.1
    virtualenv: '{{ ckan_install_path }}'
    virtualenv_site_packages: no

- name: Create directory for ckan config files
  become: true
  become_user: root
  become_method: sudo
  file: 'path={{ ckan_conf_path }} owner={{ ckan_system_user }} state=directory'

- name: Make secondary directory to link confs into
  become: true
  become_user: root
  become_method: sudo
  file: 'path=/etc/ckan/ state=directory owner={{ ckan_system_user }}'

- name: Make lib directory in ckan base
  become: true
  become_user: root
  become_method: sudo
  file: 'path={{ ckan_install_base_path }}/lib/default state=directory owner={{ ckan_system_user }}'

- name: Link conf directory to /etc/ckan
  become: true
  become_user: root
  become_method: sudo
  file: 'src={{ ckan_conf_path }} dest=/etc/ckan/default state=link'

- name: Make secondary directory to link installation into
  become: true
  become_user: root
  become_method: sudo
  file: 'path=/usr/lib/ckan state=directory owner=ckan'

- name: Install CKAN from source using PIP
  become: true
  become_user: root
  become_method: sudo
  pip:
    chdir: '{{ ckan_install_path }}'
    name: '{{ ckan_repository_address }}'
    virtualenv: '{{ ckan_install_path }}'
    editable: 'yes'

- name: Install requirements
  become: true
  become_user: root
  pip:
    virtualenv: '{{ ckan_install_path }}'
    chdir: '{{ ckan_install_path }}'
    requirements: '{{ ckan_install_path }}/src/ckan/requirements.txt'


