---

##### Some Tasks deactivated - depending on apt-repository
## Need long time to update
#- name: Update apt
#  apt: update_cache=yes
#  become: true
#  become_user: root
#  become_method: sudo

#- name: Upgrade all safe packages
#  become: true
#  become_user: root
#  become_method: sudo
#  apt: upgrade=safe

# Install Python Stuff
- name: Install python-dev, python-pip, python-virtualenv
  become: true
  become_user: root
  become_method: sudo
  apt:
    name: "{{ python }}"
  vars:
    python:
    - python2.7
    - python-pip
    - python-virtualenv
    - python-psycopg2
    - libpq-dev
- name: Install openjdk-8-jdk
  become: true
  become_user: root
  become_method: sudo
  apt:
    name: openjdk-8-jdk
# Install Git
- name: Install git-core
  become: true
  become_user: root
  become_method: sudo
  apt:
    name: git-core
# Install Database
- name: postgresql
  become: true
  become_user: root
  become_method: sudo
  apt:
    name: postgresql
# Install Redis
- name: redis-server
  become: true
  become_user: root
  become_method: sudo
  apt:
    name: redis-server
# Install solr-jetty or solr-tomcat
- name: solr-jetty || solr-tomcat
  become: true
  become_user: root
  become_method: sudo
  apt:
    name: solr-jetty