---


- name: Create directory for ckan config files
  become: true
  become_user: root
  become_method: sudo
  file: 'path={{ ckan_conf_path }} owner={{ ckan_system_user }} state=directory'

- name: Make secondary directory to link confs into
  become: true
  become_user: root
  become_method: sudo
  file: 'path=/etc/ckan/ state=directory owner={{ ckan_system_user }}'

- name: Make lib directory in ckan base
  become: true
  become_user: root
  become_method: sudo
  file: 'path={{ ckan_install_base_path }}/lib/default state=directory owner={{ ckan_system_user }}'

- name: Link conf directory to /etc/ckan
  become: true
  become_user: root
  become_method: sudo
  file: 'src={{ ckan_conf_path }} dest=/etc/ckan/default state=link'

- name: Make secondary directory to link installation into
  become: true
  become_user: root
  become_method: sudo
  file: 'path=/usr/lib/ckan state=directory owner=ckan'

- name: Run CKAN installation script
  become: true
  become_user: root
  become_method: sudo
  shell: |
    virtualenv --no-site-packages default
    . default/bin/activate
    pip install -U setuptools==36.1
    pip install --ignore-installed -e {{ ckan_repository_address }}
    pip install --ignore-installed -r default/src/ckan/pip-requirements-docs.txt
    exit
  args:
    chdir: /usr/lib/ckan
    creates: /usr/lib/ckan/default/src/ckan/ckan/config/solr/schema.xml

- name: Ensure CKAN config is present
  become: true
  become_user: root
  become_method: sudo
  template:
    src: ../../templates/default/ckan/development.ini
    dest: /etc/ckan/default/development.ini
  when: not ansible_check_mode

- name: solr schema
  become: yes
  become_user: root
  become_method: sudo
  command: mv /etc/solr/conf/schema.xml /etc/solr/conf/schema.xml.bak

- name: solr schema copy
  become: yes
  become_user: root
  become_method: sudo
  command: ln -s /usr/lib/ckan/default/src/ckan/ckan/config/solr/schema.xml /etc/solr/conf/schema.xml

#- name: solr jetty xml copy
#  become: yes
#  become_user: root
#  become_method: sudo
#  command: ln -s /etc/solr/solr-jetty.xml /var/lib/jetty9/webapps/solr.xml

- name: Ensure CKAN who.ini is symlinked
  become_user: root
  become: yes
  become_method: sudo
  file:
    src: /usr/lib/ckan//default/src/ckan/ckan/config/who.ini
    dest: /etc/ckan/default/who.ini
    state: link


- name: Initialize CKAN database
  become_user: root
  become: yes
  shell: |
    . /usr/lib/ckan/default/bin/activate
    cd /usr/lib/ckan/default/src/ckan
    paster db init -c /etc/ckan/default/development.ini
    exit

- name: Check if CKAN admin user exists
  become_user: ckan
  become: yes
  shell: |
    . /usr/lib/ckan/default/bin/activate
    cd /usr/lib/ckan/default/src/ckan
    paster --plugin=ckan user list -c /etc/ckan/default/development.ini
    exit
  changed_when: False
  register: ckan_admin_user
  notify: Restart Solr

- name: Ensure WSGI specification for CKAN is present
  become_user: root
  become: yes
  template:
    src: ../templates/default/apache2/apache.wsgi.j2
    dest: /etc/ckan/default/apache.wsgi
  notify: Restart Apache