---

- name: Enable Ckan site
  become: true
  become_user: root
  become_method: sudo
  shell: |
    a2ensite ckan_default
    a2dissite 000-default
    rm -vi /etc/nginx/sites-enabled/default
    ln -s /etc/nginx/sites-available/ckan /etc/nginx/sites-enabled/ckan_default
    service apache2 restart
    service nginx restart
    service apache2 reload
    service nginx reload
    exit